---
- hosts: all
  vars:
    targeturl: https://github.com/spring-projects/spring-petclinic/archive/1.5.x.tar.gz
    targetdir: /tmp/webserver
    username: 'Kathikeya'
  tasks:
    - name: delete file karthikeya.txt
      file:
        path: "/tmp/karthikeya.txt"
        state: absent
    - name: delete file karthikeya2.txt
      file:
        path: "/tmp/karthikeya2.txt"
        state: absent
    - name: delete file spring-petclinic-1.5.x.tar.gz
      file:
        path: "/tmp/webserver/spring-petclinic-1.5.x.tar.gz"
        state: absent
    - name: "create target directory for webserver"
      file: path={{ targetdir }} state=directory
    - name: Unarchive a file that needs to be downloaded from internet
      unarchive:
        src: '{{ targeturl }}'
        dest: '{{ targetdir }}'
        remote_src: yes
    - name: example copying file with owner and permissions
      copy:
        src: petclinic/src/main/resources/application.properties
        dest: '{{ targetdir }}'
    - name: adding template to target dir
      template:
        src: petclinic/src/main/resources/email_template.j2
        dest: "{{ targetdir }}/email.txt"
    - name: checking if file exists
      shell: cat "{{ targetdir }}/email.txt"
      register: ps
    - name: printing output
      debug:
        var: ps.stdout_lines
    - name: printing return code
      debug:
        var: ps.rc
