node(ubuntu_slave5)
{
    stage(build)
    {
        cleanWS()
        if(isUnix())
        {
            sh 'git clone -b ${BRANCH_NAME} https://github.com/sasi9k/petclinic-infra.git'
            dir('petclinic-infra/pipelines/karthik/ansible')
            {
            		    sh 'git clone -b ${BRANCH_NAME} https://github.com/sasi9k/petclinic.git'

                        sh 'ansible-playbook file.yml -i 192.168.1.221, -u desktop6izealinc'
            }
        }
    }
}